# Generated by Django 3.2.8 on 2021-11-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetableelement_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableelement',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
        migrations.AlterField(
            model_name='timetablerow',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetable.timetable'),
        ),
    ]
